### ISSUE TITLE
RetroPad icon

### ISSUE THREAD

**Issue by fr500** [libretro/retroarch-assets#110]
We have several gamepad icons that could be used in gui and for documentation but one we sorely lack is an official retropad icon.

The RetroPad is... think of it like a SNES pad + dual analogs that's the best description.

**Comment by baxysquare** [comment]
So would something like this work?  What you describe ends up looking like a Wii Classic Controller  the 8Bitdo NES30 Pro.

I started with the Libretro D-Pad and worked outward from there.

![retropad_worksheet](https://cloud.githubusercontent.com/assets/17163726/22430207/a2e40ef8-e6ca-11e6-8b09-c092f42e5ea9.png)

**Comment by hizzlekizzle** [comment]
I think that looks good! I like that stylized shape over something curvy (think: xbox or wii u pro pads). Can we get an invader above the start/select buttons?

**Comment by baxysquare** [comment]
I can add it in, but I'm hesitant to do so.  @Kivutar tends to favor icons without branding unless that branding "is" the icon (like the Cave Story or Handheld Electronic Game icons).  After shelving the work on RetroActive marked, I really do see his point.  The logos get lost when the icons get scaled down in the XMB.  

Also, when we have a RetroArch logo, we also do a version with the Lakka logo that will substitute out when using the OS instead of the app.  The best way to avoid that is to go unbranded in the first place.

Lastly, I'd like to point out that unless the branding really helps to identify the object, it's generally best to leave it off.  In this example, it's clear what the left and right icons are.  However, not everyone may be familiar with the odd shape of the Micro SD so having the logo on there helps identify what it is.  With this being a generic controller with no true real-life equivalent, is it really helpful to have a logo as part of the design?

![switch_icons](https://cloud.githubusercontent.com/assets/17163726/22432885/b2c4172e-e6d3-11e6-9fd6-b5f5cc271dd8.png)

**Comment by hizzlekizzle** [comment]
Those are very valid points, and yes, shrinking it down could be an issue with readability.

I do think the branding is helpful in the design in this case precisely because it doesn't actually exist. With no branding, it may not be clear that it's the "retropad" vs any generic gamepad. The libretro dpad is certainly a step in that same direction, though it is even more vulnerable to loss by downscaling.

I'm not married to the idea, though. You guys have done an awesome job with all of the icons so far and I trust your ability to make good decisions.

**Comment by baxysquare** [comment]
In reading and re-reading @fr500's original request, I thought a generic controller was exactly what was requested.  Since it's meant to be for "gui and for documentation," making it generic helps the end user adapt it to their respective controller of choice.

Honestly, if the Libretro logo wasn't a D-pad, I wouldn't even bother trying to add it to the icon.  It's just meant to be an easter egg of sorts.  I think that so long as the D-pad is fit to the grid like so, we should be fine with scalability.

Fun Fact:  The Libretro D-pad has offset rounded corners because I wanted it to double as a shuriken or a yashichi.  I came up with that idea for a logo redesign that never materialized. I ended up using it anyway for RetroActive and it spilled into the other themes as well.

![screen shot 2017-01-30 at 10 52 27 am](https://cloud.githubusercontent.com/assets/17163726/22434699/56d8a18a-e6da-11e6-9ce3-730e8ea2029e.png)

**Comment by fr500** [comment]
I really like that! I just don't like the "shuriken" dpad thing heh.
So you made those logos, I think they were good but I wasn't keen on that same thing.

I think working on an image would be important and I think you make fantastic work so if you're ever up to improving on your original ideas it would be very much appreciated

**Comment by baxysquare** [comment]
OK, let's give it a try with a traditional D-Pad.  That makes it look even more generic which probably better fulfills the objective anyway.

I made the original Libretro logo and wanted to see it evolve into a brand family for Lakka and RetroArch, which is why I pursued the failed redesign.  I'm open to revisiting it and improving the ideas on an ongoing basis if the team wants me to do so.  

![screen shot 2017-01-30 at 12 22 25 pm](https://cloud.githubusercontent.com/assets/17163726/22437850/e7ef2ae8-e6e6-11e6-8d18-0804e8bb0846.png)

**Comment by hizzlekizzle** [comment]
[quote="baxysquare"]I'm open to revisiting it and improving the ideas on an ongoing basis if the team wants me to do so.[/quote]
I think this would be really helpful. Compared with a lot of other projects, our brand identity is pretty basic, particularly when it comes to leveraging libretro but not RetroArch. We had talked a long time ago about needing some way for projects/frontends to communicate their libretro affiliation but never came up with anything good.

**Comment by baxysquare** [comment]
Alright, I'm willing to shift gears to logo design.  I went and dug up the original design proposal and we can work outward from that or something else if you prefer.  If you'd like to do this on GitHub, perhaps it deserves opening a new issue, while we focus on completing the RetroPad issue on this one.  If you'd prefer to handle it outside of GitHub, that's fine too.  Just let me know.

In terms of submitting the RetroPad icons, I'd like to get an answer to #111 so I can make these icons match a new naming syntax if one ends up being chosen.

**Comment by fr500** [comment]
I like it! I think that one conveys the message correctly.
In my mind the retropad looks like the nes advantage... not sure why, if you are open to experiments that could be the pad of choice.

**Comment by baxysquare** [comment]
Here's the experiment.  The NES Advantage is a challenge because the diagonals make staying on the 4x4 grid very difficult and it's such an "iconic" joystick.  To make it look a bit less like an Advantage, I dumped the turbos and inset button area.  I added an extra two action buttons and removed some of the character lines that made it distinct.  Perhaps the 4 option buttons down the side need to be removed because they are a distinguishing characteristic but they're in there for now.

![genericadvantage](https://cloud.githubusercontent.com/assets/17163726/22473881/77603b9e-e797-11e6-8750-bdc3aab787b0.png)

**Comment by fr500** [comment]
LOL I was too late to mend my comment... look at it again... I meant NES Max.
That last one is great btw!

**Comment by baxysquare** [comment]
OK here's two color variations for Systematic.  The button colors come from the Libretro, RetroArch and Lakka icons.  Which style do you like better?
![libretro---pad-c](https://cloud.githubusercontent.com/assets/17163726/22477342/e899ede0-e7a2-11e6-8d2d-7390cbda444c.png)
![libretro---pad-b](https://cloud.githubusercontent.com/assets/17163726/22477343/e89a5f82-e7a2-11e6-9885-60517856cfee.png)

**Comment by hizzlekizzle** [comment]
I like that shape a lot! I think the colored buttons are nice.

**Comment by Ferk** [comment]
Just an opinion: Maybe the shoulder buttons could be split so it becomes visible the fact that there's an L1/R1 pair and an L2/R2 pair?

I think one of the main uses of visualizing this virtual controller would be to be able to see what controls do you have to map where, to a normal controller, so this way it becomes obvious where the 2 pairs of L/R have to be placed (I'm still unsure about where L3/R3 would be supposed to be in the retropad, but I always set them to the click button of the joysticks of my my xinput controller)

**Comment by baxysquare** [comment]
@Ferk Is this what you have in mind?  In terms of visualizing L3/R3, most button maps I've seen usually point three controls to the analog stick from a single line... the X axis, Y axis and the click button.  I think that's the best way to illustrate it.

![libretro---pad-systematic](https://cloud.githubusercontent.com/assets/17163726/23282399/39600c62-f9de-11e6-86c9-fb2b2dec4805.png)

**Comment by baxysquare** [comment]
As you can see above, I added the pad icon to Monochrome, NeoActive, RetroActive and Systematic.  You can find it as "Libretro - Pad" in the PNG or SRC folders.

**Comment by HerbFargus** [comment]
![retropad](https://i.snag.gy/R0dSQi.jpg)

**Comment by fr500** [comment]
I don't like this at all

**Comment by fr500** [comment]
![39600c62-f9de-11e6-86c9-fb2b2dec4805](https://cloud.githubusercontent.com/assets/1721040/25571337/5a477240-2df4-11e7-83d7-71f854d75629.png)


This one is pretty much perfect already

**Comment by HerbFargus** [comment]
Surely we could 3d print it as a shell, would be a hit 3rd party controller!

I presume the outer triggers are L1 and R1 and the inner triggers are L2 and R2?

**Comment by Kivutar** [comment]
I agree with radius, this one is perfect.

**Comment by fr500** [comment]
So can we accept this as RetroPad's official "artwork" so it can be used in the GUI in the future, and in mockups, documents, etc?

@twinaphex

**Comment by twinaphex** [comment]
@fr500 Fine with me I guess if @kivutar and others agree with it, who am I to object?

**Comment by baxysquare** [comment]
@fr500 The icon is included in the Monochrome, NeoActive, RetroActive and Systematic sets as "Libretro - Pad".  If you need it somewhere else or in another format, let me know and I will get it added accordingly.

**Comment by fr500** [comment]
Thanks I appreciate it

**Comment by baxysquare** [comment]
I believe this issue has been resolved, so I'm going to close it for now.  If you need anything else, let me know!
