### ISSUE TITLE
PNG files are not optimised

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/retroarch-assets#116]
/retroarch/media/xmb file size

for 1,541 items

3ds cia build:
2,976,106 bytes

after optimisation with ImageOptim ([settings](http://imgur.com/a/4muB6)):
2,061,461 bytes

**Comment by baxysquare** [comment]
I went ahead and used ImageOptim on the PNG files for NeoActive, RetroActive, RetroActive Marked and Systematic.  There appeared to be some improvement in file sizes, but some of that may have been offset by the fact that I am using a modified batch command (ImageMagick Mogrify) that scales the density by 4x and then resizes the file by 25% in order to dramatically improve the anti-aliasing.  That will make all these icons look much nicer when rendered in RetroArch & Lakka.

**Comment by baxysquare** [comment]
@gingerbeardman In PR #170, @alfrix has used OptiPNG to optimize the files in the repository.  We feel that this effectively takes care of this issue, so we'll close it for now.  Thanks for your patience and let us know if you need anything else!

**Comment by gingerbeardman** [comment]
All good
