### ISSUE TITLE
Nintendo 3DS icons

### ISSUE THREAD

**Issue by j-selby** [libretro/retroarch-assets#138]
Hi!

Would it be possible to get some frontend images for the 3DS? Having black squares for the Citra core isn't very pretty :P

Thanks!

**Comment by baxysquare** [comment]
I recently added them to NeoActive, RetroActive and Systematic.  I have attached samples for your reference.  The icons may still show black boxes because I believe it is tied to the database that would require an update.  

Here's what the default sets are named:
- Nintendo New Nintendo 3DS-content.png
- Nintendo - New Nintendo 3DS.png
- Nintendo - Nintendo 3DS-content.png
- Nintendo - Nintendo 3DS.png

![nintendo - new nintendo 3ds jan-001 ka](https://cloud.githubusercontent.com/assets/17163726/26788404/4cba02d6-49ca-11e7-9279-a66b7a932e92.png)
![nintendo - new nintendo 3ds jan-001 wo](https://cloud.githubusercontent.com/assets/17163726/26788398/4caad7ac-49ca-11e7-9466-9907eff5d953.png)
![nintendo - new nintendo 3ds ktr-001 k](https://cloud.githubusercontent.com/assets/17163726/26788400/4cac9ace-49ca-11e7-816b-f02c590dcbe2.png)
![nintendo - new nintendo 3ds ktr-001 w](https://cloud.githubusercontent.com/assets/17163726/26788401/4cae6f84-49ca-11e7-9cd8-516a84804109.png)
![nintendo - new nintendo 3ds red-001 w](https://cloud.githubusercontent.com/assets/17163726/26788399/4cabf6fa-49ca-11e7-91ce-74bc7dfa9418.png)
![nintendo - new nintendo 3ds-content](https://cloud.githubusercontent.com/assets/17163726/26788402/4cb15906-49ca-11e7-90ca-414beca5309e.png)
![nintendo - new nintendo 3ds](https://cloud.githubusercontent.com/assets/17163726/26788406/4cbf2d38-49ca-11e7-9fde-ac5efa7465b7.png)
![nintendo - nintendo 3ds ctr-001 a](https://cloud.githubusercontent.com/assets/17163726/26788405/4cbeaa0c-49ca-11e7-9cc0-8cb809447798.png)
![nintendo - nintendo 3ds ctr-001 k](https://cloud.githubusercontent.com/assets/17163726/26788408/4cc3aa2a-49ca-11e7-9d56-82b459368da8.png)
![nintendo - nintendo 3ds ctr-001 q](https://cloud.githubusercontent.com/assets/17163726/26788407/4cbfb0dc-49ca-11e7-8bda-b54348b47ec8.png)
![nintendo - nintendo 3ds ctr-001 r](https://cloud.githubusercontent.com/assets/17163726/26788409/4cc79d10-49ca-11e7-99a5-df9a8532c826.png)
![nintendo - nintendo 3ds ctr-001 w](https://cloud.githubusercontent.com/assets/17163726/26788413/4cd65bfc-49ca-11e7-8da5-079c699a3bc3.png)
![nintendo - nintendo 3ds ftr-001 bk](https://cloud.githubusercontent.com/assets/17163726/26788410/4cd020fc-49ca-11e7-98cb-a0e14f2cba7d.png)
![nintendo - nintendo 3ds ftr-001 kb](https://cloud.githubusercontent.com/assets/17163726/26788411/4cd3afe2-49ca-11e7-8ee4-c463d286c6e0.png)
![nintendo - nintendo 3ds ftr-001 kr](https://cloud.githubusercontent.com/assets/17163726/26788415/4cdc3d42-49ca-11e7-8e8b-7eced8deddd6.png)
![nintendo - nintendo 3ds ftr-001 rk](https://cloud.githubusercontent.com/assets/17163726/26788412/4cd58cd6-49ca-11e7-9813-8b43fbcb7183.png)
![nintendo - nintendo 3ds spr-001 w](https://cloud.githubusercontent.com/assets/17163726/26788414/4cdb617e-49ca-11e7-8001-c6f84a70a858.png)
![nintendo - nintendo 3ds-content](https://cloud.githubusercontent.com/assets/17163726/26788416/4ce341aa-49ca-11e7-831f-f75b0a3df2f5.png)
![nintendo - nintendo 3ds](https://cloud.githubusercontent.com/assets/17163726/26788417/4ce48eb6-49ca-11e7-8d2b-3bf1e568ed27.png)

**Comment by j-selby** [comment]
5 steps ahead of me 😛 - that commit went right past.

Thanks for the good work!
