### ISSUE TITLE
[RetroActive] 'rename' icon too small

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/retroarch-assets#159]
'rename' icon too small, see:

![____tmp_screenshot_2017-08-29_01-23-38](https://user-images.githubusercontent.com/5431285/29804399-bb3f0ad2-8c58-11e7-96dd-e19a15c927b8.png)

@baxysquare

**Comment by baxysquare** [comment]
Thanks for the tip!  I made the rename icon based on the icon in monochrome, which appears to be 17x17 pixels when I open the PNG in Photoshop.  I'm going to resize it at 72x72 (or 88x88 with translucent outline) to get it consistent with the close and run icons.  Since I have more pixels to work with, I'll add some more detail to the pencil to make it more consistent with the themes.

**Comment by baxysquare** [comment]
I just updated the icon.  Hopefully you like the larger, more detailed pencil @sergiobenrocha2.  Let me know if you find anything else and we'll get it fixed up.

**Comment by sergiobenrocha2** [comment]
much better now, thanks!
