### ISSUE TITLE
xmb theme icons needed for intellivision

### ISSUE THREAD

**Issue by markwkidd** [libretro/retroarch-assets#203]
I'm very excited that the libretro ecosystem now includes FreeIntv, a Mattel Intellivision emulator. That has been one of the conspicuous gaps in the lineup of early consoles supported by RetroArch.

As of this week, FreeIntv is part of the docs, buildbot, and playlist scanner. I've been trying to help the process along as I can but graphic design is not in my portfolio. I wanted to open this issue in the hopes that someone more qualified might try to add icons for the Intellivison :)

edit:

Some visual reference points follow. Note that there were a few different designs over the years, including some consoles that were made under license.

- http://gaming.wikia.com/wiki/Intellivision
- http://gaming.wikia.com/wiki/Intellivision_II
- https://en.wikipedia.org/wiki/File:Intellivision_-_gi_1326971.jpg
- https://commons.wikimedia.org/wiki/File:SuperVideoArcade.jpg
- https://commons.wikimedia.org/wiki/File:IntellivisionII.jpg
- https://www.picquery.com/c/intellivision_Rj3jTTbiT3SYXec88WRkYMluBJ4XQ6vxqQGSrxmgv2U/

**Comment by baxysquare** [comment]
The [system icon](https://github.com/libretro/retroarch-assets/blob/master/xmb/monochrome/png/Mattel%20-%20Intellevision.png) and [media icon](https://github.com/libretro/retroarch-assets/blob/master/xmb/monochrome/png/Mattel%20-%20Intellevision-content.png) are already waiting in the wings for most themes including Monochrome, RetroActive, NeoActive and Systematic.  I believe someone on the Database team has to associate the icons with the core in order for it to show up in the XMB instead of the black square icon of doom.  @RobLoach can you confirm that is how it works?

**Comment by baxysquare** [comment]
I think I'm better at drawing icons than I am at naming them. Once #204 is merged, we should be good to go!
