### ISSUE TITLE
(Monochrome) ON and OFF are not localized

### ISSUE THREAD

**Issue by RobLoach** [libretro/retroarch-assets#273]
It's considered bad design to have icons with text on them. There are a few implications to this...

1. The icons are not localized. *On* is written as *On* in Chinese, nor is *Off* written as *Off* in Chinese.
2. Depending on the screen-size, the ON and OFF become unreadable

![on](https://user-images.githubusercontent.com/25086/50667424-2a86f500-0f87-11e9-8c6e-58ef57c5fe51.png)![off](https://user-images.githubusercontent.com/25086/50667516-9ff2c580-0f87-11e9-8acb-8a4808e9d4ba.png)

 Recommendation is to remove text from all icons across the theme.

**Comment by baxysquare** [comment]
I wonder if this needs to be pushed beyond the retroarch-assets project somehow, because "on and off" are the only ones that are not text.  I'm fine with them being changed to a text "on" or "off" for consistency and continuity.

In the meantime, I would suggest that we remove the wording, while illustrating on or off in a way that is obvious to users of any language, using the IEC power symbol.  

![on_off_proposal](https://user-images.githubusercontent.com/17163726/50709009-94ed7300-1023-11e9-90df-1b2fe3ffbc02.png)

**Comment by RobLoach** [comment]
Great mock ups. I like **Option 1** the most, and can understand where you're going with Option 2.

**Comment by baxysquare** [comment]
It's funny but I'm actually wondering if using the IEC standby symbol in this context is also bad UI design, because it's not being used to designate a power state.  Does it take away from the shutdown icon?

I also have concerns with how it looks in the monochrome and inverted art styles, so here's a white icon comparison with a blue background.  I wanted to try an oval toggle to make it more obvious which one is on and which is off.  Lastly, I wanted to see if plus and minus better represented the setting than O and I, especially since in Japanese, O represents yes, while X means no.

![on_off_proposal2](https://user-images.githubusercontent.com/17163726/50789137-9f547a80-1278-11e9-9b00-ea0740b26b02.png)

**Comment by orbea** [comment]
I think `Option B` is the best one so far.

**Comment by baxysquare** [comment]
I went ahead and implemented Option B for Automatic, Systematic, Neoactive and Retroactive.  I figure rolling these out on the non-default themes might be a good litmus test, and I can always roll them back if we get negative feedback.

**Comment by RobLoach** [comment]
I'll bring them in and test it out! Thanks a lot.

**Comment by RobLoach** [comment]
Attached is Systematic, I find it a lot more readable....

## Before

![screenshot at 2019-01-10 14-19-42](https://user-images.githubusercontent.com/25086/50991556-e9d92f80-14e2-11e9-8bbf-c59f3f50c491.png)

## After

![retroactive](https://user-images.githubusercontent.com/25086/50991563-efcf1080-14e2-11e9-8033-9d5ad8c291a2.png)

**Comment by baxysquare** [comment]
I haven't received any negative feedback about the On and Off switches having the text removed on Automatic, Systematic, Neoactive and Retroactive. Therefore I decided to modify the existing versions from monochrome for consideration.

**Comment by ofry** [comment]
Could this issue be closed now?

**Comment by RobLoach** [comment]
I see the change in Monochrome now! Looks great! :+1: 


![screenshot at 2019-02-15 15-49-25](https://user-images.githubusercontent.com/25086/52883537-51fddf80-3139-11e9-89e6-cb25f56c83c9.png)

**Comment by RobLoach** [comment]
Let's move conversation from https://github.com/libretro/retroarch-assets/pull/292 back over here. There was a desired to switch from the +/- to one of the circles at:
https://github.com/libretro/retroarch-assets/pull/292#issuecomment-466144804

**Comment by baxysquare** [comment]
I think we're really close to resolved. I believe that leaves the dot-art and pixel as the themes that need fixing.  Flat UI had already implemented a non-text solution so it was ahead of the curve on this issue

**Comment by baxysquare** [comment]
Are we leaving this open as a to-do for dot-art and pixel?

**Comment by RobLoach** [comment]
I think it's good to close :+1: THANKS A LOT! Love the new icons.
