### ISSUE TITLE
Rename FB Alpha - Arcade Games

### ISSUE THREAD

**Issue by RobLoach** [libretro/retroarch-assets#311]
FB Alpha is no longer
https://twitter.com/libretro/status/1131333664263086081

Rename "FB Alpha - Arcade Games" to one of the following?

- Arcade
- Arcade Games
- FB - Arcade
- FB - Arcade Games
- FB Neo - Arcade Games
- FinalBurn - Arcade Games
- FinalBurn - Arcade
- FinalBurn Neo - Arcade Games
- FinalBurn Neo - Arcade

Considering the majority of other playlist names use the system name, so perhaps "Arcade Games" may work.

**Comment by baxysquare** [comment]
In terms of name, I'm in favor of "Arcade Game" to be consistent with "Handheld Electronic Game." Would this effort possibly involve defining MAME and Final Burn as cores for that database/playlist?

**Comment by RobLoach** [comment]
> I'm in favor of "Arcade Game" to be consistent with "Handheld Electronic Game."

Sounds good with me. Good thinking on having it match the handheld.

> Would this effort possibly involve defining MAME and Final Burn as cores for that database/playlist?

MAME has its own database set. Shouldn't consider merging/changing those ones. I'll shoot up a PR to rename Arcade Games on libretro-database.

**Comment by RobLoach** [comment]
After further thoughts and testing it in the interface...

1. Plural vs not-plural? Having it be singular seems strange in the UI. It's listing multiple games, but shows a singular "Game", which seems strange.
2. Game? We don't list "Nintendo - Nintendo Entertainment System Game".

Considering the two points above, I'd recommend just listing "Arcade". Here's a screenshot in Ozone....

![Screenshot at 2019-05-24 09-51-49](https://user-images.githubusercontent.com/25086/58332613-96b8a700-7e09-11e9-9374-35b0e1ef9b48.png)

**Comment by baxysquare** [comment]
After reading your response and thinking about it, perhaps we should just call it "FinalBurn Neo."  After all, we don't make a distinction for all the different MAME databases.  We also don't label MAME as arcade, I assume because technically the core could handle so many other systems.

I understand the arcade ROM sets can be different for the two cores, but I wish there were a better way to display them in playlists.  For example, I recently scanned a set that was split between FinalBurn and MAME 2003.  It's so aggravating!

In general, I worry the user experience is bloated by all the different playlists that can appear after scanning a directory. I'd really like to see a bit of simplification and unification for all systems, including arcade.  But that's not the issue at hand (and I'm a hypocrite for [wanting Neo Geo rolled out of the FB database and into it's own](https://github.com/libretro/libretro-database/issues/720)).

**Comment by RobLoach** [comment]
- Handheld Electronic Game > Handheld
- FB Alpha - Arcade Games > FinalBurn

**Comment by RobLoach** [comment]
Looks like it has been renamed in [the .info file](https://github.com/libretro/libretro-super/blob/master/dist/info/fbneo_libretro.info#L9) to....
```
database = "FBNeo - Arcade Games"
```

Seems to be a good stop gap for now.
