### ISSUE TITLE
Select and Start button on SNES controller icon are offset to the right.

### ISSUE THREAD

**Issue by Atomwho** [libretro/retroarch-assets#326]
Compare to the same icon of Flat theme and real controller, I think the Select and Start button on the SNES controller icon are offset to the right.
![2019-09-20 002148](https://user-images.githubusercontent.com/4556799/65262332-b56f4600-db3c-11e9-8522-906b4ece8658.png)

**Comment by baxysquare** [comment]
I haven't contributed to FlatUI, but I will tell you that when we make icons, we try to make those elements snap to a grid.  That means buttons, D-pads and other elements will likely not be correct or might be out of proportion.  When we go off grid with design elements, it makes them so they don't scale properly and look odd in the XMB.  

Here's the icon, the real controller and the two overlaid to illustrate that technically, none of the buttons perfectly align.  The Start button and B button come close, but the rest are clearly off.  Part of that may be due to the angle of the photo, but the grid is the primary factor.

![snes_photo_icon_comparison](https://user-images.githubusercontent.com/17163726/66053150-055fec80-e4ef-11e9-8dc8-2a2ccb1ef6e2.jpg)

In the end, we're trying to get the design "close enough" that the end user thinks "hey, that's a Super NES/Famicom controller."  The artist strives to make it "iconic" rather than "realistic."  Perhaps there's a way to improve the design but I wanted you to see "behind the curtain" first.

**Comment by baxysquare** [comment]
I'm going to go ahead and close this issue.   Hopefully the explanation is sufficient.  If you feel it should be re-visited, feel free to reply.
