### ISSUE TITLE
Bluetooth Icons

### ISSUE THREAD

**Issue by RobLoach** [libretro/retroarch-assets#369]
Add `bluetooth.png` for each theme.

**Comment by RobLoach** [comment]
![unnamed](https://user-images.githubusercontent.com/25086/85929363-238e2980-b882-11ea-8e0e-435f32921480.png)

**Comment by baxysquare** [comment]
Once #387 is merged, there should be active Bluetooth icons for Automatic, Systematic, Retroactive and Neoactive.  I went with the more official oval design because I liked how it looked with the background shapes.  

I believe this should mean the majority of the themes have a bluetooth icon.  It appears that the icon has been added to all themes except for the Pixel theme.  If you feel this is sufficient to close this issue, feel free to do so.

**Comment by baxysquare** [comment]
It's been a while and this issue has been resolved in all but one theme.  I'm going to go ahead and close it, but if you feel like it needs to be reopened, please feel free to reply.
