### ISSUE TITLE
[Suggestion]Pack the pkg folder into APK

### ISSUE THREAD

**Issue by leoxxx** [libretro/retroarch-assets#378]
As shown in the title.

**Comment by baxysquare** [comment]
I'm not familiar with how this repository is integrated specifically into the Android APK.  If it's done by scripts that exist in this repository, perhaps we can make the changes you've requested.  If it's not done by this repository, then you may need to make this request with another repository within the project.  Perhaps @jdgleaver could shed some light on how or if we can take care of this here.

**Comment by jdgleaver** [comment]
This is part of the build process, so should be raised as an issue in https://github.com/libretro/libretro-super (in particular, I believe it just requires a modification to `libretro-buildbot-recipe.sh`)

It does need some consideration, though - adding these files to the apk will increase its size by ~5MB, and we're already pushing the maximum size limit imposed by Google (they're really killing us with all the new restrictions...).

BTW - @baxysquare I haven't forgotten about the theme unification project! It's just that my workload never seems to ease up...

**Comment by baxysquare** [comment]
@leoxxx It may be wise to repost this issue over on  [libretro-super](https://github.com/libretro/libretro-super) so it can be discussed and possibly implemented.  As @jdgleaver indicated, the [Android version is already being downgraded](https://www.libretro.com/index.php/retroarch-1-9-0-wont-be-releasing-on-google-play-store-for-now/), so they may have to get creative on how to make it work.  If you choose to repost, I would request that you close this issue, since there's not much we can do to solve it directly.

@jdgleaver Thanks for the update. I didn't think you'd forgotten. My contributions have been fewer and farther between due to all that is going on in life. We are seeing outside interest being shown over on #381. I agree with @alucryd  and if there's things we can do in the meantime to "trim the fat,"  I am in favor of it. I think it would benefit Arch, Android and other platforms where space and bandwidth are at a premium.

**Comment by leoxxx** [comment]
O.K. I see.
