### ISSUE TITLE
Script for converting BMP to BIN for RGUI Fonts

### ISSUE THREAD

**Issue by rtomasa** [libretro/retroarch-assets#434]
Is it feasible to get the script or a brief explanation on how to convert the font spritesheet bitmap.bmp to bitmap.bin?
I'd like to create a custom one and be able to compile in RA

**Comment by rtomasa** [comment]
Sorry, yes I was doing reference to RGUI Fonts

**Comment by rtomasa** [comment]
@DisasterMo, @trngaje, @jdgleaver
Any possibility to get that script or some details on how to generate the bin files?

**Comment by trngaje** [comment]
There is no source for reference because it is reconstructed with simple c code depending on the type of input font.
- cjk fonts are generated by .ttf and modified pixels by manual.
- extended english font are generated by png font image.
I thought about organizing it once, but i coudn't because the font distributed in each language is different,
Which font do you want to change to bin? font type (bmp, png, ttf, bdf ...). and char sets. Please give me specific information.
I can create tools and distribute sources based on specific font data, but I can't unify them for all languages.
Most of the codes are implemented by reverse engineering of  the retroarch font output part, so the codes are the same
 
-----Original Message-----

**Comment by rtomasa** [comment]
@trngaje I'm only interested in the RGUI bitmap .BMP fonts. Maybe my understanding on how it works is not correct. I saw the sprite-sheet font.bmp in the corresponding RetroArch folder and also a font.bin file that I assumed that corresponds to the binary encoded file (assumed that you create the font.bin from font.bmp using some script). Also assumed that when  compiling RA, make command will take the bin file to "generate" the font inside the C code. Maybe I'm completely wrong...

**Comment by rtomasa** [comment]
Solution provided in https://github.com/libretro/docs/issues/738

**Comment by rtomasa** [comment]
@trngaje I've finished creating and compiling my first custom font in RA and everything worked perfectly fine but the switch icons that display garbage. Do you know if this is something independent from the font sheet?
