### ISSUE TITLE
Netplay Icons

### ISSUE THREAD

**Issue by fr500** [libretro/retroarch-assets#95]
Hey, as you may or not know, we are adding a lobby browser for netplay, so we need the following:
- Netplay Rooms icon, could be a world globe or something like that
- LAN room icon
- Internet room icon

And those two should probably have a variant for password enabled rooms
Thanks a lot!

**Comment by fr500** [comment]
For the lobby browser maybe something like this;
![network300](https://cloud.githubusercontent.com/assets/1721040/22169191/5e85ee02-df40-11e6-8a8a-3b7f949da6c9.png)
Or this:
![gamesharing350](https://cloud.githubusercontent.com/assets/1721040/22169192/609c1112-df40-11e6-820f-002bc04435db.png)

**Comment by fr500** [comment]
For a lobby maybe something like:
![remoteplay300](https://cloud.githubusercontent.com/assets/1721040/22169232/8ae47504-df40-11e6-8097-4ca5fba7a52a.png)

And a small badge like this when it's password protected
![certificate350](https://cloud.githubusercontent.com/assets/1721040/22169219/7e58d154-df40-11e6-9bf2-69e4cec52bb0.png)

**Comment by CoalaJoe** [comment]
How should they be named?

**Comment by fr500** [comment]
doesn't matter, I'll just change the code to reflect that when they are

**Comment by CoalaJoe** [comment]
Sure.

netplay_server.png
lobby.png
password_protected.png

These 3?

**Comment by Tatsuya79** [comment]
netplay_server.png
netplay_lobby.png
netplay_password_protected.png

It would be great to have those icons organized.

**Comment by CoalaJoe** [comment]
Okay. For what themes?

**Comment by Kivutar** [comment]
Monochrome is the priority.

**Comment by CoalaJoe** [comment]
How about this for netplay server?
If yes, will convert it to monochrome. (Didn't find an SVG for the RetroArch logo)

![image](https://cloud.githubusercontent.com/assets/5689499/22204503/9797ba0c-e172-11e6-8111-7cfa5625046f.png)

**Comment by baxysquare** [comment]
@fr500 So to clarify, do we need three icons or five icons?  You listed:

1. Netplay Rooms icon, could be a world globe or something like that
2. LAN room icon
3. Internet room icon

but then you said "And those two should probably have a variant for password enabled rooms" which I count as

4. LAN room locked icon
5. Internet room locked icon

I'm happy to label the files as @CoalaJoe and @Tatsuya79 indicated, but it would be helpful to know how they correspond to the list.  I'm guessing they're in the same order as the request but I wanted to get it right rather than working off that assumption.

Here's what I've whipped up for RetroActive.  I'll probably change the circles to hexagons for Systematic.

![netplay_lobby](https://cloud.githubusercontent.com/assets/17163726/22213469/9b8efc5e-e151-11e6-9349-76898348775d.png)
![netplay_password_protected](https://cloud.githubusercontent.com/assets/17163726/22213470/9b91085a-e151-11e6-8df2-2dae489b9bba.png)

**Comment by CoalaJoe** [comment]
@baxysquare They look sick! Nice work!

**Comment by baxysquare** [comment]
Since I didn't hear back, I went ahead and added Netplay icons to NeoActive, RetroActive and Systematic.  In terms of naming, I matched them up to be similar to the conventions already used.  If they need to be renamed, that is fine.

- netplay - rooms: Netplay Rooms 
- netplay - rooms-locked: Netplay Rooms Locked (Probably not necessary, but it's there if you ever need it)
- netplay - iRoom: Internet room
- netplay - iRoom-locked: Internet room Locked
- netplay - LAN Room: LAN Room
- netplay - LAN Room-locked: LAN Room Locked

**Comment by baxysquare** [comment]
I went ahead and added netplay icons to Monochrome.  @fr500 let me know if there's anything else you need.

**Comment by fr500** [comment]
Hey, those look great, thanks, I didn't see this PR thanks a lot!

**Comment by baxysquare** [comment]
So would you be okay if we close this issue?  The other themes can have it added to theie to-do lists on #71 .

**Comment by fr500** [comment]
Ok, so now we have to differentiate LAN games, Lobby games, and MITM games, and any of those may have a password.

Internet games should be represented with a globe I guess, LAN games should convey that there are computers in the same network, and MITM that there is a server in the middle.

The LOCK on top of the icons makes it impossible to recognize them too.

@Kivutar was against using a world or computers for the netplay section, not sure what he thinks about for the lobby section. I tested the current icons and they are fine imho but not sure what he thinks

![image](https://user-images.githubusercontent.com/1721040/27998254-938fa99c-64d0-11e7-83e9-7e94cb884bf8.png)

**Comment by fr500** [comment]
@baxysquare imho the netplay - iroom icon is perfect, it should be renamed to:

room_internet.png

The netplay - LAN Room icon is fine too imho

should be room_lan.png

We need one for mitm though, maybe you could put a server in the center area?

should be room_mitm.png

As for password indication, maybe put a lock in the lower white thingie instead of on top of the badge?

**Comment by Kivutar** [comment]
@fr500 If we really need to differenciate rooms, then it's OK, let use it.

**Comment by fr500** [comment]
We're kinda running out of space for text with the RetroArch version included, so the icons give use a nice way to differentiate, it's either icons or we replace Nickname with (Internet | LAN | MITM)

**Comment by fr500** [comment]
Let's discuss this in the PR please. Just one place to be able to keep track better of the conversation.
https://github.com/libretro/RetroArch/pull/5160

**Comment by fr500** [comment]
I'll just leave the icons alone for now I guess.

**Comment by baxysquare** [comment]
@fr500 Sorry I've been slow to respond.

If you want to go through and rename the icons and submit a PR, Im guessing @Kivutar or @twinaphex will merge them or discuss it accordingly.  Use the current locked icons for now and I'll place those and MITM icons on my to-do list... or if someone else beats me to the punch, so be it.

I presume the icons are not actively being used by the UI so what they are named or re-named is much easier that what I proposed on #111 since those icons are currently in use.
