### ISSUE TITLE
How can edit icon and put it in Lakka

### ISSUE THREAD

**Issue by jalt91** [libretro/retroarch-assets#99]
Hi, i have an issue 

 Lakka is connect on my network and i try to find some image to edit (I want make a custom theme)
But i cant find any folder with image in.... 

How i can make a custom theme and in which folder i have to upload them ...

Thansk in advance

**Comment by CoalaJoe** [comment]
You should find the path in the directory-settings. Maybe you have to activate advanced settings in the menü-settings to see them.
![image](https://cloud.githubusercontent.com/assets/5689499/22235078/8b46463e-e1fd-11e6-9048-b3e82085aaa2.png)

**Comment by baxysquare** [comment]
From what I understand, @Kivutar or someone else on the team has to build hooks into the system to recognize a theme in the XMB directory.  That is why RetroActive showed up as a theme, but RetroActive Marked did not.  

I know this might sound backward, but when I was developing my first theme, I started by backing up monochrome and then replacing icons in the original directory.  Since there is more than one theme now, you can pick which ever theme you wish and then toggle it on via XMB.

Once you have created all the required icons, you can submit the theme via GitHub. Once it's properly vetted, it will be added as an official theme selection option in the codebase.

**Comment by markwkidd** [comment]
Whenever the next nightly build of Lakka is released, there will be a new Samba share visible on the network. (@Kivutar) Once that build is released, the process to customize themes will be:
1. download and unzip retroarch-assets on a PC by clicking on "clone or download" and selecting "download" here: https://github.com/libretro/retroarch-assets
2. copy the contents of retroarch-assets.zip to the new "Assets" samba share
3. change the Lakka "Directory" settings so that assets is set to /storage/assets

From here on you can edit existing themes or add new ones by working in the Assets share. Give it a week or two and look for this update.

**Comment by jalt91** [comment]
Thanks for the quick answer guys really appreciate ! 

i will wait for the update and try the other solution. 

Thank you again !

**Comment by jalt91** [comment]
@CoalaJoe 
When i chek my path i have this (In exemple Thumbnails)
/Storage/Thumbnails.

But when i go on my Lakka directory i can't find any storage folder... ? 

thanks in advance

**Comment by baxysquare** [comment]
@jalt91 Perhaps this might help?

[Installing Custom Themes](https://forums.libretro.com/t/installing-custom-themes/8388)

**Comment by markwkidd** [comment]
@baxysquare with Lakka, the path where those assets are stored (~/config/retroarch/assets/xmb) is read-only.

Lakka users need an extra step compared to other RetroArch installations: make a writable copy of the assets somewhere with write access (like /storage/assets) and change the RA assets path to point at this writable folder

**Comment by baxysquare** [comment]
@markwkidd Thanks for the explanation.  I use the Mac version of RetroArch for development by working directly with the package contents, so I had no idea how or if those instructions might help.

**Comment by jalt91** [comment]
So i have to create a folder name /storage/assets ?

**Comment by markwkidd** [comment]
@jalt91 Lakka should automatically create a folder named /storage/assets when it's first installed

Could you check to see if /storage/assets exists when you log in to Lakka via SSH? There should be a folder called /storage which inludes a variety of subfolders, including the roms subfolder and the system (BIOS) subfolder as well as assets

**Comment by jalt91** [comment]
@markwkidd 
https://goo.gl/photos/pkbL4ySxtXBvS25w5

This is the only folder i have dont know where is the storage folder... 

Thank for your help mark

**Comment by markwkidd** [comment]
Hi @jalt91 -- there has still not been a new official Lakka release (which would add the "Assets" Samba share) but the latest "release candidate" builds found in this forums thread should work for your purpose: https://forums.libretro.com/t/libreelec-based-images-for-testers/8485/

**Comment by Kivutar** [comment]
He can access it in SSH on the release of december.

**Comment by markwkidd** [comment]
@Kivutar I originally suggested SSH (comment https://github.com/libretro/retroarch-assets/issues/99#issuecomment-275548185) but based on the comment https://github.com/libretro/retroarch-assets/issues/99#issuecomment-275559696 this user is hoping to access the assets folder via Samba.

**Comment by Kivutar** [comment]
Oh I see, then yes, RC4 is the way to go. Sorry :)

**Comment by markwkidd** [comment]
Thanks for your work @Kivutar on Lakka and thanks for keeping an eye on this issue. My family and I have enjoyed Lakka quite a bit over the last year! Once Lakka 2.0 is released I have told myself that I will draft a guide to help users use the overlay filesystem to create new themes. Documentation is my strongest skillset 💃

**Comment by markwkidd** [comment]
@jalt91 this feature has been incorporated into Lakka. Would you mind closing your issue?

**Comment by baxysquare** [comment]
@markwkidd I'll go ahead and close the issue.  @jalt91 If you need us to re-examine this issue or run into others, let us know!
